run_type = "sampling"
device = "cuda:0"  # or "cpu"

[parameters]
model_file = "prior/libinvent.prior"
smiles_file = "data/scaffolds.smi"
output_file = "output/sampling_libinvent.csv"
num_smiles = 100
unique_molecules = true
randomize_smiles = true
